### ISSUE TITLE
error: attribute spb_background_progress_color (aka com.app.apic.photo.androidtemplate:spb_background_progress_color) not found.

### ISSUE THREAD

**Issue by AmosKorir** [rezaiyan/LevelProgressBar#1]
I have tried using this library . When  i set the spb_background_progress_color. the application fails to build.

error: attribute spb_background_progress_color (aka com.app.apic.photo.androidtemplate:spb_background_progress_color) not found.

**Comment by rezaiyan** [comment]
Hi, this attribute was in the  [1.0.0](https://github.com/rezaiyan/LevelProgressBar/releases/tag/1.0.0) version
If  you using the latest version you have to use `spb_background_color` attribute

**Comment by AmosKorir** [comment]
Thanks.
Please update the docs
